import java.util.HashMap;
import java.util.Map;

public class ErrnoException extends Exception {

    private static final Map<Integer, String> codeErrno = new HashMap<>();

    static {
        codeErrno.put(1,  "EPERM (1) Operation not permitted" );
        codeErrno.put(2,  "ENOENT (2) No such file or directory" );
        codeErrno.put(3,  "ESRCH (3) No such process" );
        codeErrno.put(4,  "EINTR (4) Interrupted system call" );
        codeErrno.put(5,  "EIO (5) I/O error" );
        codeErrno.put(6,  "ENXIO (6) No such device or address" );
        codeErrno.put(7,  "E2BIG (7) Argument list too long" );
        codeErrno.put(8,  "ENOEXEC (8) Exec format error" );
        codeErrno.put(9,  "EBADF (9) Bad file number" );
        codeErrno.put(10,  "ECHILD (10) No child processes" );
        codeErrno.put(11,  "EAGAIN (11) Try again" );
        codeErrno.put(12,  "ENOMEM (12) Out of memory" );
        codeErrno.put(13,  "EACCES (13) Permission denied" );
        codeErrno.put(14,  "EFAULT (14) Bad address" );
        codeErrno.put(15,  "ENOTBLK (15) Block device required" );
        codeErrno.put(16,  "EBUSY (16) Device or resource busy" );
        codeErrno.put(17,  "EEXIST (17) File exists" );
        codeErrno.put(18,  "EXDEV (18) Cross-device link" );
        codeErrno.put(19,  "ENODEV (19) No such device" );
        codeErrno.put(20,  "ENOTDIR (20) Not a directory" );
        codeErrno.put(21,  "EISDIR (21) Is a directory" );
        codeErrno.put(22,  "EINVAL (22) Invalid argument" );
        codeErrno.put(23,  "ENFILE (23) File table overflow" );
        codeErrno.put(24,  "EMFILE (24) Too many open files" );
        codeErrno.put(25,  "ENOTTY (25) Not a typewriter" );
        codeErrno.put(26,  "ETXTBSY (26) Text file busy" );
        codeErrno.put(27,  "EFBIG (27) File too large" );
        codeErrno.put(28,  "ENOSPC (28) No space left on device" );
        codeErrno.put(29,  "ESPIPE (29) Illegal seek" );
        codeErrno.put(30,  "EROFS (30) Read-only file system" );
        codeErrno.put(31,  "EMLINK (31) Too many links" );
        codeErrno.put(32,  "EPIPE (32) Broken pipe" );
        codeErrno.put(33,  "EDOM (33) Math argument out of domain of func" );
        codeErrno.put(34,  "ERANGE (34) Math result not representable" );
        codeErrno.put(35,  "EDEADLK (35) Resource deadlock would occur" );
        codeErrno.put(36,  "ENAMETOOLONG (36) File name too long" );
        codeErrno.put(37,  "ENOLCK (37) No record locks available" );
        codeErrno.put(38,  "ENOSYS (38) Invalid system call number" );
        codeErrno.put(39,  "ENOTEMPTY (39) Directory not empty" );
        codeErrno.put(40,  "ELOOP (40) Too many symbolic links encountered" );
        codeErrno.put(42,  "ENOMSG (42) No message of desired type" );
        codeErrno.put(43,  "EIDRM (43) Identifier removed" );
        codeErrno.put(44,  "ECHRNG (44) Channel number out of range" );
        codeErrno.put(45,  "EL2NSYNC (45) Level 2 not synchronized" );
        codeErrno.put(46,  "EL3HLT (46) Level 3 halted" );
        codeErrno.put(47,  "EL3RST (47) Level 3 reset" );
        codeErrno.put(48,  "ELNRNG (48) Link number out of range" );
        codeErrno.put(49,  "EUNATCH (49) Protocol driver not attached" );
        codeErrno.put(50,  "ENOCSI (50) No CSI structure available" );
        codeErrno.put(51,  "EL2HLT (51) Level 2 halted" );
        codeErrno.put(52,  "EBADE (52) Invalid exchange" );
        codeErrno.put(53,  "EBADR (53) Invalid request descriptor" );
        codeErrno.put(54,  "EXFULL (54) Exchange full" );
        codeErrno.put(55,  "ENOANO (55) No anode" );
        codeErrno.put(56,  "EBADRQC (56) Invalid request code" );
        codeErrno.put(57,  "EBADSLT (57) Invalid slot" );
        codeErrno.put(59,  "EBFONT (59) Bad font file format" );
        codeErrno.put(60,  "ENOSTR (60) Device not a stream" );
        codeErrno.put(61,  "ENODATA (61) No data available" );
        codeErrno.put(62,  "ETIME (62) Timer expired" );
        codeErrno.put(63,  "ENOSR (63) Out of streams resources" );
        codeErrno.put(64,  "ENONET (64) Machine is not on the network" );
        codeErrno.put(65,  "ENOPKG (65) Package not installed" );
        codeErrno.put(66,  "EREMOTE (66) Object is remote" );
        codeErrno.put(67,  "ENOLINK (67) Link has been severed" );
        codeErrno.put(68,  "EADV (68) Advertise error" );
        codeErrno.put(69,  "ESRMNT (69) Srmount error" );
        codeErrno.put(70,  "ECOMM (70) Communication error on send" );
        codeErrno.put(71,  "EPROTO (71) Protocol error" );
        codeErrno.put(72,  "EMULTIHOP (72) Multihop attempted" );
        codeErrno.put(73,  "EDOTDOT (73) RFS specific error" );
        codeErrno.put(74,  "EBADMSG (74) Not a data message" );
        codeErrno.put(75,  "EOVERFLOW (75) Value too large for defined data type" );
        codeErrno.put(76,  "ENOTUNIQ (76) Name not unique on network" );
        codeErrno.put(77,  "EBADFD (77) File descriptor in bad state" );
        codeErrno.put(78,  "EREMCHG (78) Remote address changed" );
        codeErrno.put(79,  "ELIBACC (79) Can not access a needed shared library" );
        codeErrno.put(80,  "ELIBBAD (80) Accessing a corrupted shared library" );
        codeErrno.put(81,  "ELIBSCN (81) .lib section in a.out corrupted" );
        codeErrno.put(82,  "ELIBMAX (82) Attempting to link in too many shared libraries" );
        codeErrno.put(83,  "ELIBEXEC (83) Cannot exec a shared library directly" );
        codeErrno.put(84,  "EILSEQ (84) Illegal byte sequence" );
        codeErrno.put(85,  "ERESTART (85) Interrupted system call should be restarted" );
        codeErrno.put(86,  "ESTRPIPE (86) Streams pipe error" );
        codeErrno.put(87,  "EUSERS (87) Too many users" );
        codeErrno.put(88,  "ENOTSOCK (88) Socket operation on non-socket" );
        codeErrno.put(89,  "EDESTADDRREQ (89) Destination address required" );
        codeErrno.put(90,  "EMSGSIZE (90) Message too long" );
        codeErrno.put(91,  "EPROTOTYPE (91) Protocol wrong type for socket" );
        codeErrno.put(92,  "ENOPROTOOPT (92) Protocol not available" );
        codeErrno.put(93,  "EPROTONOSUPPORT (93) Protocol not supported" );
        codeErrno.put(94,  "ESOCKTNOSUPPORT (94) Socket type not supported" );
        codeErrno.put(95,  "EOPNOTSUPP (95) Operation not supported on transport endpoint" );
        codeErrno.put(96,  "EPFNOSUPPORT (96) Protocol family not supported" );
        codeErrno.put(97,  "EAFNOSUPPORT (97) Address family not supported by protocol" );
        codeErrno.put(98,  "EADDRINUSE (98) Address already in use" );
        codeErrno.put(99,  "EADDRNOTAVAIL (99) Cannot assign requested address" );
        codeErrno.put(100,  "ENETDOWN (100) Network is down" );
        codeErrno.put(101,  "ENETUNREACH (101) Network is unreachable" );
        codeErrno.put(102,  "ENETRESET (102) Network dropped connection because of reset" );
        codeErrno.put(103,  "ECONNABORTED (103) Software caused connection abort" );
        codeErrno.put(104,  "ECONNRESET (104) Connection reset by peer" );
        codeErrno.put(105,  "ENOBUFS (105) No buffer space available" );
        codeErrno.put(106,  "EISCONN (106) Transport endpoint is already connected" );
        codeErrno.put(107,  "ENOTCONN (107) Transport endpoint is not connected" );
        codeErrno.put(108,  "ESHUTDOWN (108) Cannot send after transport endpoint shutdown" );
        codeErrno.put(109,  "ETOOMANYREFS (109) Too many references: cannot splice" );
        codeErrno.put(110,  "ETIMEDOUT (110) Connection timed out" );
        codeErrno.put(111,  "ECONNREFUSED (111) Connection refused" );
        codeErrno.put(112,  "EHOSTDOWN (112) Host is down" );
        codeErrno.put(113,  "EHOSTUNREACH (113) No route to host" );
        codeErrno.put(114,  "EALREADY (114) Operation already in progress" );
        codeErrno.put(115,  "EINPROGRESS (115) Operation now in progress" );
        codeErrno.put(116,  "ESTALE (116) Stale file handle" );
        codeErrno.put(117,  "EUCLEAN (117) Structure needs cleaning" );
        codeErrno.put(118,  "ENOTNAM (118) Not a XENIX named type file" );
        codeErrno.put(119,  "ENAVAIL (119) No XENIX semaphores available" );
        codeErrno.put(120,  "EISNAM (120) Is a named type file" );
        codeErrno.put(121,  "EREMOTEIO (121) Remote I/O error" );
        codeErrno.put(122,  "EDQUOT (122) Quota exceeded" );
        codeErrno.put(123,  "ENOMEDIUM (123) No medium found" );
        codeErrno.put(124,  "EMEDIUMTYPE (124) Wrong medium type" );
        codeErrno.put(125,  "ECANCELED (125) Operation Canceled" );
        codeErrno.put(126,  "ENOKEY (126) Required key not available" );
        codeErrno.put(127,  "EKEYEXPIRED (127) Key has expired" );
        codeErrno.put(128,  "EKEYREVOKED (128) Key has been revoked" );
        codeErrno.put(129,  "EKEYREJECTED (129) Key was rejected by service" );
        codeErrno.put(130,  "EOWNERDEAD (130) Owner died" );
        codeErrno.put(131,  "ENOTRECOVERABLE (131) State not recoverable" );
        codeErrno.put(132,  "ERFKILL (132) Operation not possible due to RF-kill" );
        codeErrno.put(133,  "EHWPOISON (133) Memory page has hardware error" );

    }

    public static final int EPERM = 1;
    public static final int ENOENT = 2;
    public static final int ESRCH = 3;
    public static final int EINTR = 4;
    public static final int EIO = 5;
    public static final int ENXIO = 6;
    public static final int E2BIG = 7;
    public static final int ENOEXEC = 8;
    public static final int EBADF = 9;
    public static final int ECHILD = 10;
    public static final int EAGAIN = 11;
    public static final int ENOMEM = 12;
    public static final int EACCES = 13;
    public static final int EFAULT = 14;
    public static final int ENOTBLK = 15;
    public static final int EBUSY = 16;
    public static final int EEXIST = 17;
    public static final int EXDEV = 18;
    public static final int ENODEV = 19;
    public static final int ENOTDIR = 20;
    public static final int EISDIR = 21;
    public static final int EINVAL = 22;
    public static final int ENFILE = 23;
    public static final int EMFILE = 24;
    public static final int ENOTTY = 25;
    public static final int ETXTBSY = 26;
    public static final int EFBIG = 27;
    public static final int ENOSPC = 28;
    public static final int ESPIPE = 29;
    public static final int EROFS = 30;
    public static final int EMLINK = 31;
    public static final int EPIPE = 32;
    public static final int EDOM = 33;
    public static final int ERANGE = 34;
    public static final int EDEADLK = 35;
    public static final int ENAMETOOLONG = 36;
    public static final int ENOLCK = 37;
    public static final int ENOSYS = 38;
    public static final int ENOTEMPTY = 39;
    public static final int ELOOP = 40;
    public static final int ENOMSG = 42;
    public static final int EIDRM = 43;
    public static final int ECHRNG = 44;
    public static final int EL2NSYNC = 45;
    public static final int EL3HLT = 46;
    public static final int EL3RST = 47;
    public static final int ELNRNG = 48;
    public static final int EUNATCH = 49;
    public static final int ENOCSI = 50;
    public static final int EL2HLT = 51;
    public static final int EBADE = 52;
    public static final int EBADR = 53;
    public static final int EXFULL = 54;
    public static final int ENOANO = 55;
    public static final int EBADRQC = 56;
    public static final int EBADSLT = 57;
    public static final int EBFONT = 59;
    public static final int ENOSTR = 60;
    public static final int ENODATA = 61;
    public static final int ETIME = 62;
    public static final int ENOSR = 63;
    public static final int ENONET = 64;
    public static final int ENOPKG = 65;
    public static final int EREMOTE = 66;
    public static final int ENOLINK = 67;
    public static final int EADV = 68;
    public static final int ESRMNT = 69;
    public static final int ECOMM = 70;
    public static final int EPROTO = 71;
    public static final int EMULTIHOP = 72;
    public static final int EDOTDOT = 73;
    public static final int EBADMSG = 74;
    public static final int EOVERFLOW = 75;
    public static final int ENOTUNIQ = 76;
    public static final int EBADFD = 77;
    public static final int EREMCHG = 78;
    public static final int ELIBACC = 79;
    public static final int ELIBBAD = 80;
    public static final int ELIBSCN = 81;
    public static final int ELIBMAX = 82;
    public static final int ELIBEXEC = 83;
    public static final int EILSEQ = 84;
    public static final int ERESTART = 85;
    public static final int ESTRPIPE = 86;
    public static final int EUSERS = 87;
    public static final int ENOTSOCK = 88;
    public static final int EDESTADDRREQ = 89;
    public static final int EMSGSIZE = 90;
    public static final int EPROTOTYPE = 91;
    public static final int ENOPROTOOPT = 92;
    public static final int EPROTONOSUPPORT = 93;
    public static final int ESOCKTNOSUPPORT = 94;
    public static final int EOPNOTSUPP = 95;
    public static final int EPFNOSUPPORT = 96;
    public static final int EAFNOSUPPORT = 97;
    public static final int EADDRINUSE = 98;
    public static final int EADDRNOTAVAIL = 99;
    public static final int ENETDOWN = 100;
    public static final int ENETUNREACH = 101;
    public static final int ENETRESET = 102;
    public static final int ECONNABORTED = 103;
    public static final int ECONNRESET = 104;
    public static final int ENOBUFS = 105;
    public static final int EISCONN = 106;
    public static final int ENOTCONN = 107;
    public static final int ESHUTDOWN = 108;
    public static final int ETOOMANYREFS = 109;
    public static final int ETIMEDOUT = 110;
    public static final int ECONNREFUSED = 111;
    public static final int EHOSTDOWN = 112;
    public static final int EHOSTUNREACH = 113;
    public static final int EALREADY = 114;
    public static final int EINPROGRESS = 115;
    public static final int ESTALE = 116;
    public static final int EUCLEAN = 117;
    public static final int ENOTNAM = 118;
    public static final int ENAVAIL = 119;
    public static final int EISNAM = 120;
    public static final int EREMOTEIO = 121;
    public static final int EDQUOT = 122;
    public static final int ENOMEDIUM = 123;
    public static final int EMEDIUMTYPE = 124;
    public static final int ECANCELED = 125;
    public static final int ENOKEY = 126;
    public static final int EKEYEXPIRED = 127;
    public static final int EKEYREVOKED = 128;
    public static final int EKEYREJECTED = 129;
    public static final int EOWNERDEAD = 130;
    public static final int ENOTRECOVERABLE = 131;
    public static final int ERFKILL = 132;
    public static final int EHWPOISON = 133;


    private String message;
    private Integer errnoValue;
   
    public ErrnoException(String message_) {        
        message = message_;
    }

    public ErrnoException(int errno_) {
        errnoValue = Integer.valueOf(errno_);
        message = codeErrno.get(errno_ );
        if (message == null) {
            message = "Unknwon errno value ("+errno_+")";
        }
    }

    public Integer getErrnoValue() {
        return errnoValue;
    }

    @Override
    public String getMessage() {
        return message;
    }
}
